# Generated by Django 4.0.2 on 2022-02-15 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('teams', models.IntegerField(choices=[(1, 'One Two  Three Four'), (2, 'One Three  Two Four'), (3, 'One Four  Two Three')], default=1)),
                ('players', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('complexity', models.IntegerField(choices=[(1, 'Easy'), (2, 'Intermediate'), (3, 'Hard')])),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.room')),
                ('state', models.IntegerField(choices=[(1, 'Newborn'), (2, 'Playing'), (3, 'Waiting'), (4, 'Finished')])),
                ('round_start_time', models.DateTimeField(blank=True, null=True)),
                ('current_turn', models.IntegerField(blank=True, null=True)),
                ('current_round', models.IntegerField(blank=True, null=True)),
                ('total_round_count', models.IntegerField(default=8)),
                ('round_duration_seconds', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', related_query_name='word', to='core.match')),
            ],
        ),
    ]
