# Generated by Django 4.0.2 on 2022-02-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room4',
            name='teams',
            field=models.IntegerField(choices=[(1, 'One Two  Three Four'), (2, 'One Three  Two Four'), (3, 'One Four  Two Three')], default=1),
        ),
    ]
